import numpy as np
array=np.array([0.1,1,2,5])
print("The array is:",array)
print("The length of array is:",array.size)
print("The dimension of array is:",array.ndim)
print("The datatype of array is:",array.dtype)
print("The shape of array is:",array.shape)
Twodarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("The twodarray elements is:",Twodarray)
print("The length of twdarray is:",Twodarray.size)
print("The dimension of array is:",Twodarray.ndim)
print("The datatype of array is:",Twodarray.dtype)
print("The shape of array is:",Twodarray.shape)
Threedarray=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("The elements in threedarray is:",Threedarray)
print("The length of threedarray is:",Threedarray.size)
print("The dimension of array is:",Threedarray.ndim)
print("The data type of array is:",Threedarray.dtype)
print("The shape of array is:",Threedarray.shape)
Fourdarray=np.array([[[[1.1,2.2,3.3,4.4],[1.2,2.2,3.2,4.2],[1.3,2.3,3.3,4.3]]]])
print("The Fourdarray is:",Fourdarray)
print("The dimension of array is:",Fourdarray.ndim)
print("The size of Fourdarray is:",Fourdarray.size)
print("The data type of array is:",Fourdarray.dtype)
print("The shape of array is:",Fourdarray.shape)
onesarray=np.ones(5,int)
print(onesarray)
# zeroarray=np.zero()
# print(zeroarray)
array=np.random.rand(2,2,3)
print(array)
print(array.size)
